GET http://localhost:3001/api/v1/experiences

###

GET http://localhost:3001/api/v1/experiences/5fb54390c554140dd034d2b7


###

POST http://localhost:3001/api/v1/projects

Content-Type: application/json

{
    "titre": "Mon nouveau projet",
    "descriptif": "Portfolio fait avec next js",
    "vignette": "https://picsum.photos/200",
    "lien": "http://localhost:3000/projects/new",
    "startDate": "2020-11-05T23:00:00.000Z",
    "technos": "React, Next JS, Node JS"
}